services:
    phpbbworld.pmread.listener:
        class: phpbbworld\pmread\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@request'
        tags:
            - { name: event.listener }

    phpbbworld.pmread.pm_manager:
        class: phpbbworld\pmread\service\pm_manager
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@service_container'

    phpbbworld.pmread.cron.task.prune_pms:
        class: phpbbworld\pmread\cron\task\prune_pms
        arguments:
            - '@config'
            - '@phpbbworld.pmread.pm_manager'
            - '@log'
        calls:
            - [set_name, ['phpbbworld.pmread.cron.task.prune_pms']]
        tags:
            - { name: cron.task }
